image: node:14-alpine

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - yarn
    - yarn test

deploy:
  stage: deploy
  script:
    - |
      echo $'registry=https://registry.yarnpkg.com
      //npm.sangre.dev/:_authToken='"$NPM_TOKEN"'
      @sangre-fp:registry=https://npm.sangre.dev
      ' > /root/.npmrc
    - npm i -g microbundle@next --unsafe
    - npm publish
  only:
    - tags
